### ISSUE TITLE
What should we read?

### ISSUE THREAD

**Issue by MylesBorins** [mangajs/bookclub#1]
Open to ideas

**Comment by makenai** [comment]
I haven't read a ton of manga before, but I'd like to read more of them. One I read recently that was pretty amazing was Shigeru Mizuki's Showa 1926-1939 - and there are more books in the series up to 1989. It takes an interesting angle because it intermixes the author's life as a boy growing up in that period of Japan with detailed historical accounts.

This is pretty effective. You do get an omniscient big picture view of what's going on that can only really be appreciated in hindsight after the details and causes and effects are fully understood. You also get a picture of how these happenings can affect the life of a person who is living through them without a clue about what's really going on or what will happen next. It gets me thinking quite a bit about how we'll look back on these times and especially around the happenings of this US presidential cycle.

He has also published one that is a biography of Hitler that is similar in detail and scope to the Showa books.

That said.. I'm also game for something a little less heavy!

**Comment by MylesBorins** [comment]
we should still do this

**Comment by MylesBorins** [comment]
we didn't do it
